config/routes.rb
Blog::Application.routes.draw do

  resources :posts

  
  namespace :admin do
    resources :posts do
        post :edit
    end
  end

  root :to => 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title
  validates :content, :title, :presence => true
  validates :content, :length => {:maximum => 1000}
  validates :title, :length => {:maximum => 100}
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  layout "admin"

  def create
    Post.create(params[:post])
    redirect_to :admin_posts
  end

  def new

  end

  def edit
    @post = Post.find(params[:post_id])
  end

  def update
    Post.find(params[:id]).update_attributes(params[:post])
    redirect_to :admin_posts
  end

  def index
    @posts = Post.all
  end

  def destroy
    Post.find(params[:id]).destroy
    redirect_to admin_posts_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/admin/_head.html.haml
.navbar.navbar-inverse.navbar-fixed-top
  .navbar-inner
    .container
      %a.btn.btn-navbar
        %span.icon-bar
      =link_to "Blog on Rails", "/", :class => 'brand'
      .nav-collapse
        %ul.nav
          %li.active
            =link_to "Posts", admin_posts_path 
          %li
            =link_to "Create", new_admin_post_path, :class => "create_post"

app/views/admin/posts/_form.html.haml
= form_for([:admin, @post.nil? ? Post.new : @post])  do |f|
  .fields
    =f.label "Title", {:class => "text-left"}
    =f.text_field :title, {:id => 'title', :class => "span12"}
  .fields
    =f.label "Content"
    =f.text_area :content, {:id => 'content', :class => "span12"}
  =f.submit "Update", {:class => 'btn'}

app/views/admin/posts/edit.html.haml
.container
  %h2= "Edit Post"
  =render "form"

app/views/admin/posts/index.html.haml
.container
  %h4.page-header= "Posts"
  - unless @posts.nil?
    .table#posts
      - @posts.each do |post|
        %div 
          =link_to post.title, admin_post_edit_path(post), :class => 'title', :method => :edit
          =link_to "Delete", admin_post_path(post), :class => "pull-right delete",:id => post.id, :method => :delete
  - else
    .notice= "Not post found"

app/views/admin/posts/new.html.haml
.container
  %h2= "New Post"
  =render "form"

app/views/layouts/admin.html.haml
!!! 5
%html
  %head
    %title= 'Blog'
    = stylesheet_link_tag    "application"
    = csrf_meta_tags
  %body
    = render "/admin/head"
    = yield
    = javascript_include_tag "application"

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= 'Blog'
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = yield

app/views/posts/index.html.haml
.container
  - unless @posts.nil?
    - @posts.try(:each) do |post|
      .post
        %h3= link_to post.title, post_path(post)
        %p= post.content
  - else
    .notice= "Not post found"

app/views/posts/new.html.haml
%h2= "New Post"
= form_for(Post.new)  do |f|
  .fields
    =f.label "Title"
    =f.text_field :title, {:id => 'title'}
  .fields
    =f.label "Content"
    =f.text_area :content, {:id => 'content'}
  =f.submit

app/views/posts/show.html.haml
.container
  - if @post.present?
    %h3.title= @post.title
    .content= @post.content
    .createdAt="Created at #{@post.created_at}"

  - else
    .notice= "not found"

  = link_to 'View Posts',  posts_path